apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-sina
  namespace: bootcamp
  labels:
    app: broker-sina
spec:
  selector:
    matchLabels:
      app: broker-sina
  template:
    metadata:
      labels:
        app: broker-sina
        service_monitoring: bootcamp
    spec:
      containers:
        - name: sina-broker-container
          image: dockerproxy.bale.ai/sinamna/bale_broker:v4
          ports:
            - name: grpc
              containerPort: 8086
            - name: prometheus
              containerPort: 8000
  replicas: 1
