apiVersion: v1
kind: Service
metadata:
  name: broker-sina-nodeport
spec:
  type: NodePort
  selector:
    app: broker-sina-pod
  ports:
  - port: 8000
    targetPort: 8000
    name: prometheus-log
  - port: 8086
    targetPort: 8086
    name: grpc-server
    
